name: Python tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install testing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install paddle on ubuntu
      run: |
        pip install paddlepaddle

    - name: Install requirements
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
